### ISSUE TITLE
Please use the NLTK Downloader to obtain the resource:

### ISSUE THREAD

**Issue by tisttsf** [pncnmnp/Bookmark-Manager#4]
```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\nltk\corpus\util.py", line 83, in __load
    root = nltk.data.find("{}/{}".format(self.subdir, zip_name))
  File "C:\Python39\lib\site-packages\nltk\data.py", line 585, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
```
How to solve that problem?

**Comment by pncnmnp** [comment]
@tisttsf You can solve this by running the following command in your Python shell - 
```python
import nltk
nltk.download('stopwords')
```
Or you can use the command-line - 
```bash
python -m nltk.downloader stopwords
```
Relevant Links:
[1] https://stackoverflow.com/questions/41610543/corpora-stopwords-not-found-when-import-nltk-library/49048876
[2] https://www.nltk.org/data.html
